[general]
email = "ravishankar.sivasubramaniam@gmail.com"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 5000
address = "0.0.0.0"
allowRunOnSave = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"